// <auto-generated />
using System;
using Infra.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(SgpsDbContexto))]
    [Migration("20230416204657_config inicial")]
    partial class configinicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sgps")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GisaDominio.Entidades.Consulta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PacienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("PrestadorId")
                        .HasColumnType("bigint");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Consulta", "sgps");
                });

            modelBuilder.Entity("GisaDominio.Entidades.Exame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ConveniadoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PacienteId")
                        .HasColumnType("bigint");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<long>("TipoExameId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TipoExameId");

                    b.ToTable("Exame", "sgps");
                });

            modelBuilder.Entity("GisaDominio.Entidades.TipoExame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoExame", "sgps");
                });

            modelBuilder.Entity("GisaDominio.Entidades.Exame", b =>
                {
                    b.HasOne("GisaDominio.Entidades.TipoExame", "TipoExame")
                        .WithMany()
                        .HasForeignKey("TipoExameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoExame");
                });
#pragma warning restore 612, 618
        }
    }
}
